[tool.poetry]
name = "ontogpt"
version = "0.3.7"
description = "OntoGPT"
authors = ["Chris Mungall <cjmungall@lbl.gov>", "Krishna Bandi <krishna.bandi@invitae.com>"]
license = "BSD-3"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.7"
"ruamel.yaml" = "0.18.5"
Jinja2 = {version = "3.1.3", optional = true}
aiohttp = "3.9.3"
airium = "0.2.6"
beautifulsoup4 = "4.12.3"
bioc = "2.1"
cachier = "2.2.2"
class-resolver = "0.4.2"
click = "8.1.7"
eutils = "0.6.0"
fastapi = {version = "0.109.2", optional = true}
gilda = "1.0.0"
gpt4 = "0.0.1"
httpx = "0.26.0"
huggingface_hub  = {version = "0.15.1", extras = ["huggingface"], optional = true}
inflect = "7.0.0"
inflection = "0.5.1"
jsonlines = "4.0.0"
linkml = "1.6.10"
linkml-owl = "0.3.0"
llm = "0.13.1"
llm-gpt4all = {version = "0.2", extras = ["gpt4all"], optional = true}
myst-parser = {version = "0.18.1", extras = ["docs"], optional = true}
nlpcloud = "1.1.45"
oaklib = "0.5.25"
openai = "1.10.0"
pydantic = "2.6.0"
pystow = "0.5.2"
python-multipart = "0.0.5"
recipe-scrapers = {version = ">=14.35.0", extras = ["recipes"], optional = true}
requests = "2.31.0"
requests-cache = "1.1.1"
sphinx = {version = "5.3.0", extras = ["docs"], optional = true}
sphinx-autodoc-typehints = {version = "1.19.4", extras = ["docs"], optional = true}
sphinx-click = {version = "4.3.0", extras = ["docs"], optional = true}
sphinx-rtd-theme = {version = "1.0.0", extras = ["docs"], optional = true}
streamlit = "1.31.0"
textract = {version = "*", extras = ["textract"], optional = true}
tiktoken = "0.5.2"
uvicorn = {version = ">=0.20.0", optional = true}
wikipedia = "1.4.0"
wikipedia-api = "0.6.0"
dpath = "^2.1.6"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "8.0.0"
setuptools = "69.0.3"
tox = "4.12.1"
mkdocs-mermaid2-plugin = "0.6.0"

[tool.poetry.scripts]
ontogpt = "ontogpt.cli:main"
web-ontogpt = "ontogpt.webapp.main:start"

[tool.poetry.extras]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "sphinx-autodoc-typehints",
    "sphinx-click",
    "myst-parser"
    ]
web = [
    "fastapi",
    "uvicorn",
    "Jinja2"
]
recipes = [
    "recipe-scrapers"
]
gpt4all = [
    "llm-gpt4all"
]
textract = [
    "textract"
]
huggingface = [
    "huggingface_hub"
]

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"
seaborn = "^0.12.2"
papermill = "^2.4.0"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "pep440"

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310"]

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
reverse_relative = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
