name: Deploy Documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

    paths:
    - 'docs/*/*.md'

jobs:
  build-docs:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Python3
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install uv
      run: pip install uv

    #----------------------------------------------
    #  Create documentation and deploy.
    #----------------------------------------------
    - name: Create local docs
      run: |
        touch docs/.nojekyll
        uv run make all_docs
        uv run make gh-deploy
